-- ============================================================================
-- E-COMMERCE COMPANY CASE STUDY - SQL SOLUTION SCRIPT
-- COMPATIBLE WITH MYSQL WORKBENCH VERSION 8.0.40
-- STRICT COMPLIANCE: 100% UPPERCASE CHARACTERS ACROSS ALL COMMANDS, COMMENTS, 
-- TABLE NAMES, COLUMN NAMES, ALIASES, AND STRING LITERALS.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SECTION 1: DATABASE SETUP AND SCHEMA CREATION
-- ----------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;
USE ECOMMERCE_DB;

-- DROP EXISTING TABLES IF RE-RUNNING SCRIPT TO ENSURE CLEAN ENVIRONMENT
DROP TABLE IF EXISTS ORDERDETAILS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CUSTOMERS;

-- 1. CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL
);

-- 2. PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL
);

-- 3. ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    TOTAL_AMOUNT INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- 4. ORDERDETAILS TABLE
CREATE TABLE ORDERDETAILS (
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE_PER_UNIT INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID, PRICE_PER_UNIT),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- ----------------------------------------------------------------------------
-- SECTION 2: DATA INTEGRITY & VERIFICATION CHECKS
-- ----------------------------------------------------------------------------

-- CHECK 2.1: VERIFY RECORD COUNTS FOR ALL IMPORTED TABLES
SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM CUSTOMERS
UNION ALL
SELECT 'PRODUCTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM PRODUCTS
UNION ALL
SELECT 'ORDERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM ORDERS
UNION ALL
SELECT 'ORDERDETAILS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM ORDERDETAILS;

-- CHECK 2.2: REVENUE RECONCILIATION BETWEEN ORDERS AND ORDERDETAILS
WITH CALCULATED_ORDER_TOTALS AS (
    SELECT 
        ORDER_ID,
        SUM(QUANTITY * PRICE_PER_UNIT) AS CALCULATED_TOTAL
    FROM ORDERDETAILS
    GROUP BY ORDER_ID
)
SELECT 
    O.ORDER_ID,
    O.TOTAL_AMOUNT AS RECORDED_AMOUNT,
    C.CALCULATED_TOTAL,
    (O.TOTAL_AMOUNT - C.CALCULATED_TOTAL) AS VARIANCE
FROM ORDERS O
JOIN CALCULATED_ORDER_TOTALS C ON O.ORDER_ID = C.ORDER_ID
WHERE (O.TOTAL_AMOUNT - C.CALCULATED_TOTAL) <> 0;

-- ----------------------------------------------------------------------------
-- SECTION 3: VERTICAL 1 - CUSTOMER INSIGHTS
-- ----------------------------------------------------------------------------

-- QUERY 1.1: GEOGRAPHIC PERFORMANCE & REVENUE CONTRIBUTION BY CITY
-- ANALYZES TOTAL CUSTOMERS, ACTIVE BUYERS, ORDER COUNT, AND TOTAL REVENUE BY LOCATION.
SELECT 
    C.LOCATION,
    COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_REGISTERED_CUSTOMERS,
    COUNT(DISTINCT O.CUSTOMER_ID) AS ACTIVE_BUYERS,
    COUNT(O.ORDER_ID) AS TOTAL_ORDERS_PLACED,
    COALESCE(SUM(O.TOTAL_AMOUNT), 0) AS TOTAL_REVENUE_GENERATED,
    ROUND(COALESCE(SUM(O.TOTAL_AMOUNT), 0) / NULLIF(COUNT(O.ORDER_ID), 0), 2) AS AVERAGE_ORDER_VALUE
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.LOCATION
ORDER BY TOTAL_REVENUE_GENERATED DESC;

-- QUERY 1.2: TOP 10 HIGH-VALUE CUSTOMERS (VIP CUSTOMER IDENTIFICATION)
-- RANKS CUSTOMERS BASED ON TOTAL SPEND, ORDER FREQUENCY, AND AVERAGE SPEND PER ORDER.
WITH CUSTOMER_SPEND AS (
    SELECT 
        C.CUSTOMER_ID,
        C.NAME AS CUSTOMER_NAME,
        C.LOCATION,
        COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
        SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT,
        ROUND(AVG(O.TOTAL_AMOUNT), 2) AS AVG_ORDER_VALUE,
        DENSE_RANK() OVER (ORDER BY SUM(O.TOTAL_AMOUNT) DESC) AS SPEND_RANK
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.NAME, C.LOCATION
)
SELECT 
    SPEND_RANK,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    LOCATION,
    TOTAL_ORDERS,
    TOTAL_SPENT,
    AVG_ORDER_VALUE
FROM CUSTOMER_SPEND
WHERE SPEND_RANK <= 10
ORDER BY SPEND_RANK ASC;

-- QUERY 1.3: CUSTOMER ORDER FREQUENCY SEGMENTATION
-- SEGMENTS CUSTOMERS BY PURCHASING FREQUENCY (ONE-TIME, REPEAT, HEAVY BUYERS).
WITH CUSTOMER_ORDER_COUNTS AS (
    SELECT 
        C.CUSTOMER_ID,
        COUNT(O.ORDER_ID) AS ORDER_COUNT
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID
)
SELECT 
    CASE 
        WHEN ORDER_COUNT = 0 THEN '01. INACTIVE (0 ORDERS)'
        WHEN ORDER_COUNT = 1 THEN '02. ONE-TIME BUYER (1 ORDER)'
        WHEN ORDER_COUNT BETWEEN 2 AND 4 THEN '03. REPEAT BUYER (2-4 ORDERS)'
        ELSE '04. HEAVY BUYER (5+ ORDERS)'
    END AS CUSTOMER_SEGMENT,
    COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT,
    ROUND(COUNT(CUSTOMER_ID) * 100.0 / SUM(COUNT(CUSTOMER_ID)) OVER (), 2) AS PERCENTAGE_OF_BASE
FROM CUSTOMER_ORDER_COUNTS
GROUP BY 
    CASE 
        WHEN ORDER_COUNT = 0 THEN '01. INACTIVE (0 ORDERS)'
        WHEN ORDER_COUNT = 1 THEN '02. ONE-TIME BUYER (1 ORDER)'
        WHEN ORDER_COUNT BETWEEN 2 AND 4 THEN '03. REPEAT BUYER (2-4 ORDERS)'
        ELSE '04. HEAVY BUYER (5+ ORDERS)'
    END
ORDER BY CUSTOMER_SEGMENT ASC;

-- QUERY 1.4: INACTIVE CUSTOMER IDENTIFICATION (ZERO PURCHASE HISTORY)
-- EXTRACTS CUSTOMERS WHO HAVE NOT PLACED ANY ORDERS FOR TARGETED RE-ENGAGEMENT.
SELECT 
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    C.LOCATION
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL
ORDER BY C.LOCATION ASC, C.CUSTOMER_ID ASC;

-- ----------------------------------------------------------------------------
-- SECTION 4: VERTICAL 2 - PRODUCT ANALYSIS
-- ----------------------------------------------------------------------------

-- QUERY 2.1: PRODUCT PERFORMANCE RANKING (REVENUE & VOLUME SOLD)
-- EVALUATES TOTAL UNITS SOLD, ORDER COUNT, AND TOTAL REVENUE GENERATED PER PRODUCT.
SELECT 
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    P.PRICE AS UNIT_CATALOG_PRICE,
    SUM(OD.QUANTITY) AS TOTAL_UNITS_SOLD,
    COUNT(DISTINCT OD.ORDER_ID) AS TOTAL_ORDERS_CONTAINING_PRODUCT,
    SUM(OD.QUANTITY * OD.PRICE_PER_UNIT) AS TOTAL_REVENUE,
    ROUND(SUM(OD.QUANTITY * OD.PRICE_PER_UNIT) * 100.0 / SUM(SUM(OD.QUANTITY * OD.PRICE_PER_UNIT)) OVER (), 2) AS REVENUE_SHARE_PERCENT
FROM PRODUCTS P
JOIN ORDERDETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME, P.CATEGORY, P.PRICE
ORDER BY TOTAL_REVENUE DESC;

-- QUERY 2.2: CATEGORY PERFORMANCE BREAKDOWN
-- AGGREGATES REVENUE, VOLUME, AND AVERAGE ITEM PRICE ACROSS PRODUCT CATEGORIES.
SELECT 
    P.CATEGORY,
    COUNT(DISTINCT P.PRODUCT_ID) AS TOTAL_PRODUCTS_IN_CATEGORY,
    SUM(OD.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(OD.QUANTITY * OD.PRICE_PER_UNIT) AS CATEGORY_REVENUE,
    ROUND(AVG(P.PRICE), 2) AS AVERAGE_PRODUCT_PRICE,
    ROUND(SUM(OD.QUANTITY * OD.PRICE_PER_UNIT) * 100.0 / (SELECT SUM(QUANTITY * PRICE_PER_UNIT) FROM ORDERDETAILS), 2) AS CATEGORY_REVENUE_PERCENT
FROM PRODUCTS P
JOIN ORDERDETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY CATEGORY_REVENUE DESC;

-- QUERY 2.3: PRODUCT CO-PURCHASE / CROSS-SELLING PAIR ANALYSIS
-- IDENTIFIES FREQUENT PRODUCT COMBINATIONS BOUGHT TOGETHER IN THE SAME ORDER.
SELECT 
    P1.NAME AS PRODUCT_A,
    P2.NAME AS PRODUCT_B,
    COUNT(*) AS TIMES_PURCHASED_TOGETHER
FROM ORDERDETAILS OD1
JOIN ORDERDETAILS OD2 ON OD1.ORDER_ID = OD2.ORDER_ID AND OD1.PRODUCT_ID < OD2.PRODUCT_ID
JOIN PRODUCTS P1 ON OD1.PRODUCT_ID = P1.PRODUCT_ID
JOIN PRODUCTS P2 ON OD2.PRODUCT_ID = P2.PRODUCT_ID
GROUP BY P1.NAME, P2.NAME
HAVING COUNT(*) >= 10
ORDER BY TIMES_PURCHASED_TOGETHER DESC;

-- ----------------------------------------------------------------------------
-- SECTION 5: VERTICAL 3 - SALES OPTIMIZATION
-- ----------------------------------------------------------------------------

-- QUERY 5.1: MONTHLY SALES TRENDS & AVERAGE ORDER VALUE (AOV)
-- TRACKS MONTHLY ORDER VOLUME, TOTAL REVENUE, AND AVERAGE ORDER VALUE OVER TIME.
SELECT 
    CONCAT(YEAR(O.ORDER_DATE), '-', LPAD(MONTH(O.ORDER_DATE), 2, '0')) AS SALES_MONTH,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) AS MONTHLY_REVENUE,
    ROUND(AVG(O.TOTAL_AMOUNT), 2) AS AVERAGE_ORDER_VALUE,
    SUM(SUM(O.TOTAL_AMOUNT)) OVER (ORDER BY CONCAT(YEAR(O.ORDER_DATE), '-', LPAD(MONTH(O.ORDER_DATE), 2, '0'))) AS CUMULATIVE_REVENUE
FROM ORDERS O
GROUP BY CONCAT(YEAR(O.ORDER_DATE), '-', LPAD(MONTH(O.ORDER_DATE), 2, '0'))
ORDER BY SALES_MONTH ASC;

-- QUERY 5.2: ORDER VALUE SEGMENTATION & BASKET SIZE DISTRIBUTION
-- BUCKETS ORDERS BY SPEND AMOUNT TO UNDERSTAND PURCHASING TIER DISTRIBUTIONS.
WITH ORDER_TIERS AS (
    SELECT 
        ORDER_ID,
        TOTAL_AMOUNT,
        CASE 
            WHEN TOTAL_AMOUNT < 25000 THEN '01. LOW VALUE (< 25K)'
            WHEN TOTAL_AMOUNT BETWEEN 25000 AND 100000 THEN '02. MID VALUE (25K - 100K)'
            WHEN TOTAL_AMOUNT BETWEEN 100001 AND 200000 THEN '03. HIGH VALUE (100K - 200K)'
            ELSE '04. PREMIUM VALUE (> 200K)'
        END AS VALUE_TIER
    FROM ORDERS
)
SELECT 
    VALUE_TIER,
    COUNT(ORDER_ID) AS ORDER_COUNT,
    SUM(TOTAL_AMOUNT) AS TIER_TOTAL_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS AVERAGE_TIER_SPEND,
    ROUND(SUM(TOTAL_AMOUNT) * 100.0 / (SELECT SUM(TOTAL_AMOUNT) FROM ORDERS), 2) AS REVENUE_CONTRIBUTION_PERCENT
FROM ORDER_TIERS
GROUP BY VALUE_TIER
ORDER BY VALUE_TIER ASC;

-- QUERY 5.3: PEAK MONTHLY REVENUE ANALYSIS
-- HIGHLIGHTS TOP PERFORMING MONTHS TO ASSIST MARKETING CAMPAIGN TIMING.
SELECT 
    CONCAT(YEAR(ORDER_DATE), '-', LPAD(MONTH(ORDER_DATE), 2, '0')) AS SALES_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    DENSE_RANK() OVER (ORDER BY SUM(TOTAL_AMOUNT) DESC) AS REVENUE_RANK
FROM ORDERS
GROUP BY CONCAT(YEAR(ORDER_DATE), '-', LPAD(MONTH(ORDER_DATE), 2, '0'))
ORDER BY REVENUE_RANK ASC;

-- ----------------------------------------------------------------------------
-- SECTION 6: VERTICAL 4 - INVENTORY MANAGEMENT
-- ----------------------------------------------------------------------------

-- QUERY 6.1: INVENTORY VELOCITY & STOCK RUN-RATE ANALYSIS
-- CALCULATES MONTHLY CONSUMPTION RATE AND AVERAGE UNITS PER ORDER.
WITH MONTH_SPAN AS (
    SELECT TIMESTAMPDIFF(MONTH, MIN(ORDER_DATE), MAX(ORDER_DATE)) + 1 AS TOTAL_OPERATIONAL_MONTHS
    FROM ORDERS
)
SELECT 
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    SUM(OD.QUANTITY) AS TOTAL_UNITS_SOLD,
    ROUND(SUM(OD.QUANTITY) * 1.0 / M.TOTAL_OPERATIONAL_MONTHS, 2) AS AVG_MONTHLY_UNIT_DEMAND,
    ROUND(SUM(OD.QUANTITY) * 1.0 / COUNT(DISTINCT OD.ORDER_ID), 2) AS AVG_UNITS_PER_ORDER
FROM PRODUCTS P
JOIN ORDERDETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
CROSS JOIN MONTH_SPAN M
GROUP BY P.PRODUCT_ID, P.NAME, P.CATEGORY, M.TOTAL_OPERATIONAL_MONTHS
ORDER BY AVG_MONTHLY_UNIT_DEMAND DESC;

-- QUERY 6.2: STOCK MOVEMENT CLASSIFICATION (FAST VS SLOW MOVING PRODUCTS)
-- CATEGORIZES PRODUCTS BASED ON TOTAL VOLUME DEMAND TO GUIDE RESTOCKING PRIORITIES.
SELECT 
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    SUM(OD.QUANTITY) AS TOTAL_UNITS_SOLD,
    CASE 
        WHEN SUM(OD.QUANTITY) >= 140 THEN 'FAST MOVING (HIGH STOCKOUT RISK)'
        WHEN SUM(OD.QUANTITY) BETWEEN 115 AND 139 THEN 'MODERATE MOVING (STABLE)'
        ELSE 'SLOW MOVING (MONITOR OVERSTOCK)'
    END AS INVENTORY_VELOCITY_CLASS
FROM PRODUCTS P
JOIN ORDERDETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME, P.CATEGORY
ORDER BY TOTAL_UNITS_SOLD DESC;

-- QUERY 6.3: RECOMMENDED QUARTERLY RESTOCKING QUANTITIES
-- GENERATES SAFETY STOCK AND RECOMMENDED 90-DAY REORDER QUANTITIES (WITH 20% BUFFER).
WITH PRODUCT_DEMAND AS (
    SELECT 
        P.PRODUCT_ID,
        P.NAME AS PRODUCT_NAME,
        P.CATEGORY,
        SUM(OD.QUANTITY) AS ANNUAL_UNITS_SOLD
    FROM PRODUCTS P
    JOIN ORDERDETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY P.PRODUCT_ID, P.NAME, P.CATEGORY
)
SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    ANNUAL_UNITS_SOLD,
    ROUND(ANNUAL_UNITS_SOLD / 12.0, 0) AS MONTHLY_BASE_DEMAND,
    ROUND((ANNUAL_UNITS_SOLD / 12.0) * 3 * 1.20, 0) AS RECOMMENDED_QUARTERLY_REORDER_QTY
FROM PRODUCT_DEMAND
ORDER BY RECOMMENDED_QUARTERLY_REORDER_QTY DESC;

-- ============================================================================
-- END OF SCRIPT
-- ============================================================================
